#!/bin/sh
# Report the number of dangling volumes
# Created by Frank IJskes for Rijkswaterstaat

echo "<<<docker_dangling_volumes>>>"

CNT=$(sudo docker volume ls -fq dangling=true | wc -l)

#CNT=$((CNT-1))

echo "Number of dangling volumes: $CNT"
